In [40]:
from pathlib import Path
import pandas as pd

In [41]:
# Load Dataset

abs_path = Path.cwd()
data_address = abs_path.parent.parent / 'data/' / 'US.csv'
df = pd.read_csv(data_address)

In [42]:
# dataset info

df.info() # RangeIndex: 2845342 entries, 0 to 2845341

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2845342 entries, 0 to 2845341
Data columns (total 47 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Severity               int64
 2   Start_Time             object
 3   End_Time               object
 4   Start_Lat              float64
 5   Start_Lng              float64
 6   End_Lat                float64
 7   End_Lng                float64
 8   Distance(mi)           float64
 9   Description            object
 10  Number                 float64
 11  Street                 object
 12  Side                   object
 13  City                   object
 14  County                 object
 15  State                  object
 16  Zipcode                object
 17  Country                object
 18  Timezone               object
 19  Airport_Code           object
 20  Weather_Timestamp      object
 21  Temperature(F)         float64
 22  Wind_Chill(F)          float64
 23  Humidity(%)            float64
 24  Pressure(in)           float64
 25  Visibility(mi)         float64
 26  Wind_Direction         object
 27  Wind_Speed(mph)        float64
 28  Precipitation(in)      float64
 29  Weather_Condition      object
 30  Amenity                bool
 31  Bump                   bool
 32  Crossing               bool
 33  Give_Way               bool
 34  Junction               bool
 35  No_Exit                bool
 36  Railway                bool
 37  Roundabout             bool
 38  Station                bool
 39  Stop                   bool
 40  Traffic_Calming        bool
 41  Traffic_Signal         bool
 42  Turning_Loop           bool
 43  Sunrise_Sunset         object
 44  Civil_Twilight         object
 45  Nautical_Twilight      object
 46  Astronomical_Twilight  object
dtypes: bool(13), float64(13), int64(1), object(20)
memory usage: 773.4+ MB

In [43]:
# return some statistics values

df.describe()

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Number,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,2.845342e+06,2.845342e+06,2.845342e+06,2.845342e+06,2.845342e+06,2.845342e+06,1.101431e+06,2.776068e+06,2.375699e+06,2.772250e+06,2.786142e+06,2.774796e+06,2.687398e+06,2.295884e+06
mean,2.137572e+00,3.624520e+01,-9.711463e+01,3.624532e+01,-9.711439e+01,7.026779e-01,8.089408e+03,6.179356e+01,5.965823e+01,6.436545e+01,2.947234e+01,9.099391e+00,7.395044e+00,7.016940e-03
std,4.787216e-01,5.363797e+00,1.831782e+01,5.363873e+00,1.831763e+01,1.560361e+00,1.836009e+04,1.862263e+01,2.116097e+01,2.287457e+01,1.045286e+00,2.717546e+00,5.527454e+00,9.348831e-02
min,1.000000e+00,2.456603e+01,-1.245481e+02,2.456601e+01,-1.245457e+02,0.000000e+00,0.000000e+00,-8.900000e+01,-8.900000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.000000e+00,3.344517e+01,-1.180331e+02,3.344628e+01,-1.180333e+02,5.200000e-02,1.270000e+03,5.000000e+01,4.600000e+01,4.800000e+01,2.931000e+01,1.000000e+01,3.500000e+00,0.000000e+00
50%,2.000000e+00,3.609861e+01,-9.241808e+01,3.609799e+01,-9.241772e+01,2.440000e-01,4.007000e+03,6.400000e+01,6.300000e+01,6.700000e+01,2.982000e+01,1.000000e+01,7.000000e+00,0.000000e+00
75%,2.000000e+00,4.016024e+01,-8.037243e+01,4.016105e+01,-8.037338e+01,7.640000e-01,9.567000e+03,7.600000e+01,7.600000e+01,8.300000e+01,3.001000e+01,1.000000e+01,1.000000e+01,0.000000e+00
max,4.000000e+00,4.900058e+01,-6.711317e+01,4.907500e+01,-6.710924e+01,1.551860e+02,9.999997e+06,1.960000e+02,1.960000e+02,1.000000e+02,5.890000e+01,1.400000e+02,1.087000e+03,2.400000e+01

In [44]:
df.sample(5)

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
959191,A-1309192,2,2021-05-04 10:54:30,2021-05-04 19:25:36,40.642576,-73.979976,40.645447,-73.973102,0.411,Stationary traffic on NY-27 from Old New Utrec...,...,False,True,False,False,False,False,Day,Day,Day,Day
2577112,A-2777113,2,2019-04-12 16:16:12,2019-04-12 16:44:28,39.030399,-94.361180,39.026887,-94.360724,0.244,At Bowlin Rd/Lakewood Blvd/Exit 14 - Accident....,...,False,False,False,False,False,False,Day,Day,Day,Day
1269303,A-1569304,2,2021-01-17 05:03:59.000000000,2021-01-17 07:08:43.000000000,35.174761,-90.018272,35.185790,-90.017395,0.764,Incident on I-40 EB near MM 1 Expect long delays.,...,False,False,False,False,False,False,Night,Night,Night,Night
1577498,A-1877499,2,2020-12-30 15:43:50,2020-12-30 18:05:11,33.496122,-81.758661,33.496864,-81.760773,0.132,Incident on RICHARDSONS LAKE RD near WOODVALLE...,...,False,False,False,False,False,False,Day,Day,Day,Day
1655087,A-155088,2,2017-03-08 07:37:53,2017-03-08 13:37:53,35.183788,-80.751118,35.183618,-80.751866,0.044,At Cedars East Ct - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [45]:
# Drop Unnecessary Columns

df.drop(['ID', 'Description', 'End_Time', 'Number', 
         'Street', 'Side', 'Zipcode', 'Country', 'Timezone',
        'Airport_Code', 'Weather_Timestamp'], 
       axis = 1, inplace=True)

In [46]:
# Drop Missing Values

df.dropna(subset=['City', 'State', 'Weather_Condition'], inplace=True)

In [47]:
# Add Weekday, Hour, Month Columns

df['Start_Time'] = pd.to_datetime(df['Start_Time'])
df['Weekday'] = df['Start_Time'].dt.day_name()
df['Hour'] = df['Start_Time'].dt.hour
df['Month'] = df['Start_Time'].dt.month

In [48]:
# Save US_Clean.csv

df.to_csv('../../data/Cleaned_US.csv', index=False)

In [49]:
# Load Clean

data_address = Path.cwd().parent.parent / 'data/' / 'Cleaned_US.csv'
cleaned_df = pd.read_csv(data_address)

In [50]:
# Cleaned Info

cleaned_df.info() # RangeIndex: 2774575 entries, 0 to 2774574

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2774575 entries, 0 to 2774574
Data columns (total 39 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Severity               int64
 1   Start_Time             object
 2   Start_Lat              float64
 3   Start_Lng              float64
 4   End_Lat                float64
 5   End_Lng                float64
 6   Distance(mi)           float64
 7   City                   object
 8   County                 object
 9   State                  object
 10  Temperature(F)         float64
 11  Wind_Chill(F)          float64
 12  Humidity(%)            float64
 13  Pressure(in)           float64
 14  Visibility(mi)         float64
 15  Wind_Direction         object
 16  Wind_Speed(mph)        float64
 17  Precipitation(in)      float64
 18  Weather_Condition      object
 19  Amenity                bool
 20  Bump                   bool
 21  Crossing               bool
 22  Give_Way               bool
 23  Junction               bool
 24  No_Exit                bool
 25  Railway                bool
 26  Roundabout             bool
 27  Station                bool
 28  Stop                   bool
 29  Traffic_Calming        bool
 30  Traffic_Signal         bool
 31  Turning_Loop           bool
 32  Sunrise_Sunset         object
 33  Civil_Twilight         object
 34  Nautical_Twilight      object
 35  Astronomical_Twilight  object
 36  Weekday                object
 37  Hour                   int64
 38  Month                  int64
dtypes: bool(13), float64(12), int64(3), object(11)
memory usage: 584.8+ MB