## Load Dataset

In [4]:
import pandas 
from pathlib import Path
import numpy as np

In [5]:
abs_path = Path.cwd()
print(abs_path)
data_address = abs_path.parent.parent / 'data/'

/mnt/c/Users/user/desktop/Project/code/Transportaion-Pipline

In [6]:
# Concate multiple chunks together for train
df1 = pandas.read_csv(data_address / 'US1.csv' )
df2 = pandas.read_csv(data_address / 'US15.csv' )
df3 = pandas.read_csv(data_address / 'US30.csv' )
df4 = pandas.read_csv(data_address / 'US45.csv' )
df5 = pandas.read_csv(data_address / 'US57.csv' )

dfList = [df1, df2, df3, df4, df5]

df = pd.concat(dfList)

In [7]:
df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.112060,-83.031870,3.230,Between Sawmill Rd/Exit 20 and OH-315/Olentang...,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.865420,-84.062800,39.865010,-84.048730,0.747,At OH-4/OH-235/Exit 41 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Night
2,A-3,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.102660,-84.524680,39.102090,-84.523960,0.055,At I-71/US-50/Exit 1 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Day
3,A-4,2,2016-02-08 06:51:45,2016-02-08 12:51:45,41.062130,-81.537840,41.062170,-81.535470,0.123,At Dart Ave/Exit 21 - Accident.,...,False,False,False,False,False,False,Night,Night,Day,Day
4,A-5,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,39.170476,-84.501798,0.500,At Mitchell Ave/Exit 6 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45337,A-2845338,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.998880,-117.370940,0.543,At Market St - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
45338,A-2845339,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.765550,-117.153630,0.338,At Camino Del Rio/Mission Center Rd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
45339,A-2845340,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.777400,-117.857270,0.561,At Glassell St/Grand Ave - Accident. in the ri...,...,False,False,False,False,False,False,Day,Day,Day,Day
45340,A-2845341,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.983110,-118.395650,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
45341,A-2845342,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.137360,-117.239340,0.537,At Highland Ave/Arden Ave - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 245342 entries, 0 to 45341
Data columns (total 47 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     245342 non-null  object
 1   Severity               245342 non-null  int64
 2   Start_Time             245342 non-null  object
 3   End_Time               245342 non-null  object
 4   Start_Lat              245342 non-null  float64
 5   Start_Lng              245342 non-null  float64
 6   End_Lat                245342 non-null  float64
 7   End_Lng                245342 non-null  float64
 8   Distance(mi)           245342 non-null  float64
 9   Description            245342 non-null  object
 10  Number                 85325 non-null   float64
 11  Street                 245342 non-null  object
 12  Side                   245342 non-null  object
 13  City                   245322 non-null  object
 14  County                 245342 non-null  object
 15  State                  245342 non-null  object
 16  Zipcode                245197 non-null  object
 17  Country                245342 non-null  object
 18  Timezone               244973 non-null  object
 19  Airport_Code           244557 non-null  object
 20  Weather_Timestamp      241736 non-null  object
 21  Temperature(F)         239956 non-null  float64
 22  Wind_Chill(F)          203313 non-null  float64
 23  Humidity(%)            239722 non-null  float64
 24  Pressure(in)           240596 non-null  float64
 25  Visibility(mi)         239375 non-null  float64
 26  Wind_Direction         239532 non-null  object
 27  Wind_Speed(mph)        232303 non-null  float64
 28  Precipitation(in)      191772 non-null  float64
 29  Weather_Condition      239371 non-null  object
 30  Amenity                245342 non-null  bool
 31  Bump                   245342 non-null  bool
 32  Crossing               245342 non-null  bool
 33  Give_Way               245342 non-null  bool
 34  Junction               245342 non-null  bool
 35  No_Exit                245342 non-null  bool
 36  Railway                245342 non-null  bool
 37  Roundabout             245342 non-null  bool
 38  Station                245342 non-null  bool
 39  Stop                   245342 non-null  bool
 40  Traffic_Calming        245342 non-null  bool
 41  Traffic_Signal         245342 non-null  bool
 42  Turning_Loop           245342 non-null  bool
 43  Sunrise_Sunset         245139 non-null  object
 44  Civil_Twilight         245139 non-null  object
 45  Nautical_Twilight      245139 non-null  object
 46  Astronomical_Twilight  245139 non-null  object
dtypes: bool(13), float64(13), int64(1), object(20)
memory usage: 68.6+ MB

### Handling Missing Values

In [9]:
# Handling Missing Values with AVERAGE
def fill_average(feature):
    df[feature] = df[feature].fillna(round(df[feature].mean(), 1))

In [10]:
fill_average('Temperature(F)')
fill_average('Wind_Chill(F)')
fill_average('Humidity(%)')
fill_average('Pressure(in)')
fill_average('Visibility(mi)')
fill_average('Wind_Speed(mph)')

### Select Weather Condition

In [11]:
weather_features = ['Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)',
                   'Pressure(in)', 'Visibility(mi)', 'Wind_Speed(mph)']

In [12]:
# X features and y target

X = df[weather_features]
y = df['Severity']

In [13]:
X

,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph)
0,42.1,36.1,58.0,29.76,10.0,10.4
1,36.9,62.6,91.0,29.68,10.0,7.8
2,36.0,62.6,97.0,29.70,10.0,7.8
3,39.0,62.6,55.0,29.65,10.0,7.8
4,37.0,29.8,93.0,29.69,10.0,10.4
...,...,...,...,...,...,...
45337,86.0,86.0,40.0,28.92,10.0,13.0
45338,70.0,70.0,73.0,29.39,10.0,6.0
45339,73.0,73.0,64.0,29.74,10.0,10.0
45340,71.0,71.0,81.0,29.62,10.0,8.0
45341,79.0,79.0,47.0,28.63,7.0,7.0

In [14]:
y

0        3
1        2
2        2
3        2
4        3
        ..
45337    2
45338    2
45339    2
45340    2
45341    2
Name: Severity, Length: 245342, dtype: int64

### Random Forest Part

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [21]:
RF = RandomForestClassifier()
RF = RF.fit(X_train, Y_train)
Y_pred = RF.predict(X_test)

In [22]:
metrics.accuracy_score(Y_test, Y_pred)

0.8308660493022042